import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/providers/NextAuthProvider";
import Navbar from "@/components/Navbar";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/authOptions";
import { userService } from "./services/userService";
import UserProvider from "@/providers/UserProvider";
import { CartProvider } from "@/providers/CartProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Umana Property",
  description: "Generated by Md Abdul Kyum",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  const user = session?.accessToken ? await userService.getMe(session?.accessToken) : null;

  return (
    <html lang="en">
      <head>
        <script src="https://js.stripe.com/v3/" async></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <UserProvider user={user}>
            <CartProvider>
              <Navbar></Navbar>
              
              {children}

            </CartProvider>
          </UserProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
