import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/providers/NextAuthProvider";
import Navbar from "@/components/Navbar";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/authOptions";
import { userService } from "./services/userService";
import UserProvider from "@/providers/UserProvider";
import { Toaster } from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Umana Property",
  description: "Generated by Md Abdul Kyum",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  const user = session?.accessToken ? await userService.getMe(session?.accessToken) : null;

  return (
    <html lang="en">
      <head>
        <script src="https://js.stripe.com/v3/" async></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <UserProvider user={user}>

              <Navbar></Navbar>
              
              {children}
              
              <Toaster
                   position="top-center"
                   toastOptions={{
                     style: {
                       background: "#ffffff",   
                       color: "#111827",        
                       border: "1px solid #e5e7eb",
                       fontSize: "14px",
                     },
                   }}
                 />  

          </UserProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
